<?php

/**
 * @file
 * Provides custom commerce order functionality for OE.
 */

/**
 * Implementation of hook_menu().
 */
function medicalidfashions_commerce_print_order_menu() {
  $items['user/%user/order/%commerce_order/print'] = array(
    'title' => 'Clean Print Order',
    'page callback' => 'medicalidfashions_commerce_print_order_view',
    'page arguments' => array(1, 3),
    'access callback' => 'medicalidfashions_commerce_print_order_access',
    'access arguments' => array(1, 3),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Access callback to determine if user should be able to view printable order.
 */
function medicalidfashions_commerce_print_order_access($account, $order) {
  global $user;

  // If the current user is the order owner.
  if ($user->uid == $order->uid) {
    return TRUE;
  }

  // If the user has a session matching the order (anonymous checkout).
  if (commerce_cart_order_session_exists($order->order_id, TRUE)) {
    return TRUE;
  }

  // Default to the view permission for all commerce_order entities.
  return user_access('view any commerce_order entity');
}

/**
 * Page callback for order print view.
 */
function medicalidfashions_commerce_print_order_view($user, $order) {
  global $base_url;

  $order_wrapper = entity_metadata_wrapper('commerce_order', $order);


  $order_view = reset(entity_view('commerce_order', array($order)));
  print '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN" "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>Outdoored.com Order #' . $order->order_number . '</title>';
  print '<link type="text/css" href="' . $base_url . '/' . drupal_get_path('module', 'medicalidfashions_commerce_print_order') . '/medicalidfashions_commerce_print_order.css" rel="stylesheet" />';
  // print drupal_get_css();
  print '</head><body>';
  $order_view = entity_view('commerce_order', array($order));
  print '<h1>Medical ID Fashions</h1>';
  print '<h2>Order ' . $order->order_id . ' - ' . $order_wrapper->field_order_source->value() . ' - ' . format_date($order->created, 'custom', 'm/d/y') . '</h2>';

  $line_items = &$order_view['commerce_order'][$order->order_id]['commerce_line_items'][0]['#markup'];
  $line_items = str_replace('Unit price', 'Price', $line_items);

  $order_view['commerce_order'][$order->order_id]['field_order_donation']['#title'] = 'Donation';

  print render($order_view);
  print '</body></html>';
  exit();
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function medicalidfashions_commerce_print_order_menu_local_tasks_alter(&$data, $router_item, $root_path) {

  // Create a menu link for user order page.
  if ($root_path == 'user/%/orders/%') {
    $user_id = $router_item['original_map'][1];
    $order_id = $router_item['original_map'][3];
    $item = menu_get_item('user/' . $user_id . '/order/' . $order_id . '/print');
  }

  // Create a menu link for admin order page.
  if ($root_path == 'admin/commerce/orders/%') {
    $order_id = $router_item['original_map'][3];
    $order = commerce_order_load($order_id);
    $user_id = $order->uid;
    $item = menu_get_item('user/' . $user_id . '/order/' . $order_id . '/print');
  }

  if ($item['access']) {
    $item['title'] = t('Print this order');
    $data['actions']['output'][] = array(
      '#theme' => 'menu_local_action',
      '#link' => $item,
    );
  }
}
