<?php
/**
 * @file checkout_pane_terms.module
 * Provides an additional checkout pane: Terms and Conditions.
 */

/**
 * Implements hook_commerce_checkout_pane_info().
 *
 * This is where we define the name of the pane, related information, and
 * the base name of all the form builder functions used to present the
 * pane.
 */
function checkout_pane_terms_commerce_checkout_pane_info() {

  $panes['checkout_pane_terms'] = array(
    'title' => t('Terms and Conditions'),
    'base' => 'checkout_pane_terms_pane',

    // The checkout page where this should be displayed by default.
    'page' => 'checkout',
    'weight' => -5,

    // The form functions could be found in another file...
    // 'file' => 'includes/pane.inc',
  );

  return $panes;
}


/**
 * Terms and Conditions Pane: form callback.
 *
 * This is a standard FAPI form which will be presented in the pane.
 * The form gathers and stores information from $order->data, an array which
 * can be populated with free-form keys and values.
 */
function checkout_pane_terms_pane_checkout_form($form, &$form_state, $checkout_pane, $order) {
  // Load the T&C from the legal module.
  $query =  db_query("SELECT conditions FROM legal_conditions ORDER BY tc_id DESC LIMIT 1");
  $record = $query-> fetchObject();
  $conditions_text = $record->conditions;

  $pane_form['legal'] = array(
    '#type' => 'fieldset',
    '#weight' => 29,
  );

  $pane_form['legal']['conditions'] = array(
    '#type' => 'textarea',
    '#title' => t('Terms & Conditions'),
    '#default_value' => $conditions_text,
    '#value' => $conditions_text,
    '#rows' => 10,
    '#weight' => 0,
    '#attributes' => array('readonly' => 'readonly'),
  );

  $pane_form['legal']['terms_and_conditions'] = array(
    '#type' => 'checkbox',
    '#title' => t('I agree to the above terms'),
    '#default_value' => isset($order->data['terms_and_conditions']) ? $order->data['terms_and_conditions'] : FALSE,
    '#required' => TRUE,
  );

  return $pane_form;
}

/**
 * Terms and Conditions pane: validation callback.
 */
/* -- Delete this line if you want to use this function
function checkout_pane_terms_pane_checkout_form_validate($form, &$form_state, $checkout_pane, $order) {
  if ( isset($form_state['values']['checkout_pane_terms']['legal']['terms_and_conditions']) &&
    ($form_state['values']['checkout_pane_terms']['legal']['terms_and_conditions'] == 1)
    ) {
    return TRUE;
  }
  return FALSE;
}
// */

/**
 * Terms and Conditions pane: checkout form submission callback.
 */
function checkout_pane_terms_pane_checkout_form_submit($form, &$form_state, $checkout_pane, $order) {
  if (!empty($form_state['values'][$checkout_pane['pane_id']])) {
    $pane_values = $form_state['values'][$checkout_pane['pane_id']];
    $order->data['terms_and_conditions'] = $pane_values['legal']['terms_and_conditions'];
  }
}

/**
 * Terms and Conditions pane: presents the information we've collected in the Review checkout
 * pane.
 */
/* -- Delete this line if you want to use this function
function checkout_pane_terms_pane_review($form, $form_state, $checkout_pane, $order) {

  $content['terms_and_conditions'] = array(
    '#type' => 'item',
    '#title' => t('terms_and_conditions'),
    '#markup' => check_plain($order->data['terms_and_conditions']),
  );
  return drupal_render($content);
}
// */
