; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.39"

; Modules
projects[views_bulk_operations][subdir] = "contrib"
projects[views_bulk_operations][version] = "3.3"

projects[addressfield][subdir] = "contrib"
projects[addressfield][version] = "1.1"

projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc5"

projects[admin_views][subdir] = "contrib"
projects[admin_views][version] = "1.5"

projects[adminimal_admin_menu][subdir] = "contrib"
projects[adminimal_admin_menu][version] = "1.6"

projects[advanced_help][subdir] = "contrib"
projects[advanced_help][version] = "1.3"

projects[block_class][subdir] = "contrib"
projects[block_class][version] = "2.1"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.9"

projects[charts][subdir] = "contrib"
projects[charts][version] = "2.0-rc1"

projects[cloudflare][subdir] = "contrib"
projects[cloudflare][version] = "1.0-beta4"

projects[commerce][subdir] = "contrib"
projects[commerce][version] = "1.11"

projects[commerce_admin_order_advanced][subdir] = "contrib"
projects[commerce_admin_order_advanced][version] = "1.x-dev"
projects[commerce_admin_order_advanced][revision] = "609b767"

projects[commerce_authnet][subdir] = "contrib"
projects[commerce_authnet][version] = "1.3"

projects[commerce_braintree][subdir] = "contrib"
projects[commerce_braintree][version] = "2.x-dev"
projects[commerce_braintree][revision] = "864d410"

projects[commerce_custom_product][subdir] = "contrib"
projects[commerce_custom_product][version] = "1.0-beta2"

projects[commerce_extra_panes][subdir] = "contrib"
projects[commerce_extra_panes][version] = "1.x-dev"
projects[commerce_extra_panes][revision] = "bd2cfb0"

projects[commerce_fieldgroup_panes][subdir] = "contrib"
projects[commerce_fieldgroup_panes][version] = "1.0"

projects[commerce_google_analytics][subdir] = "contrib"
projects[commerce_google_analytics][version] = "2.0-beta2"

projects[commerce_option][subdir] = "contrib"
projects[commerce_option][version] = "1.0-beta2"

projects[commerce_paypal][subdir] = "contrib"
projects[commerce_paypal][version] = "2.3"

projects[commerce_physical][subdir] = "contrib"
projects[commerce_physical][version] = "1.x-dev"
projects[commerce_physical][revision] = "e2a8866"

projects[commerce_post_affiliate_pro][subdir] = "contrib"
projects[commerce_post_affiliate_pro][version] = "1.x-dev"
projects[commerce_post_affiliate_pro][revision] = "5522fec"

projects[commerce_pricing_attributes][subdir] = "contrib"
projects[commerce_pricing_attributes][version] = "1.0-beta4"

projects[commerce_product_attributes][subdir] = "contrib"
projects[commerce_product_attributes][version] = "1.0-beta3"

projects[commerce_reports][subdir] = "contrib"
projects[commerce_reports][version] = "4.0-beta3"

projects[commerce_shipping][subdir] = "contrib"
projects[commerce_shipping][version] = "2.2"

projects[commerce_ups][subdir] = "contrib"
projects[commerce_ups][version] = "2.0"

projects[commerce_vbo_views][subdir] = "contrib"
projects[commerce_vbo_views][version] = "1.2"

projects[context][subdir] = "contrib"
projects[context][version] = "3.6"

projects[facetapi][subdir] = "contrib"
projects[facetapi][version] = "1.5"

projects[date][subdir] = "contrib"
projects[date][version] = "2.8"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.5"

projects[draggableviews][subdir] = "contrib"
projects[draggableviews][version] = "2.1"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.6"

projects[entityreference][subdir] = "contrib"
projects[entityreference][version] = "1.1"

projects[eva][subdir] = "contrib"
projects[eva][version] = "1.2"

projects[extlink][subdir] = "contrib"
projects[extlink][version] = "1.12"

projects[features][subdir] = "contrib"
projects[features][version] = "2.6"

projects[field_collection][subdir] = "contrib"
projects[field_collection][version] = "1.0-beta8"

projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.4"

projects[media][subdir] = "contrib"
projects[media][version] = "1.5"

projects[flexslider][subdir] = "contrib"
projects[flexslider][version] = "2.0-rc1"

projects[ga_push][subdir] = "contrib"
projects[ga_push][version] = "1.x-dev"
projects[ga_push][revision] = "f6a1813"

projects[globalredirect][subdir] = "contrib"
projects[globalredirect][version] = "1.5"

projects[google_analytics][subdir] = "contrib"
projects[google_analytics][version] = "2.x-dev"
projects[google_analytics][revision] = "6770d8f"

projects[panels][subdir] = "contrib"
projects[panels][version] = "3.5"

projects[image_url_formatter][subdir] = "contrib"
projects[image_url_formatter][version] = "1.4"

projects[imagezoom][subdir] = "contrib"
projects[imagezoom][version] = "2.0-beta2"

projects[inline_entity_form][subdir] = "contrib"
projects[inline_entity_form][version] = "1.6"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "3.0-alpha2"

projects[legal][subdir] = "contrib"
projects[legal][version] = "1.5"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2"

projects[link][subdir] = "contrib"
projects[link][version] = "1.3"

projects[mailsystem][subdir] = "contrib"
projects[mailsystem][version] = "2.34"

projects[mandrill][subdir] = "contrib"
projects[mandrill][version] = "1.6"

projects[message][subdir] = "contrib"
projects[message][version] = "1.10"

projects[message_notify][subdir] = "contrib"
projects[message_notify][version] = "2.5"

projects[metatag][subdir] = "contrib"
projects[metatag][version] = "1.7"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "2.0"

projects[multiform][subdir] = "contrib"
projects[multiform][version] = "1.1"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[physical][subdir] = "contrib"
projects[physical][version] = "1.x-dev"
projects[physical][revision] = "32e1a38"

projects[redirect][subdir] = "contrib"
projects[redirect][version] = "1.0-rc3"

projects[rules][subdir] = "contrib"
projects[rules][version] = "2.9"

projects[search404][subdir] = "contrib"
projects[search404][version] = "1.3"

projects[search_api][subdir] = "contrib"
projects[search_api][version] = "1.x-dev"
projects[search_api][revision] = "11dcade"

projects[search_api_db][subdir] = "contrib"
projects[search_api_db][version] = "1.5"

projects[select_or_other][subdir] = "contrib"
projects[select_or_other][version] = "2.22"

projects[site_map][subdir] = "contrib"
projects[site_map][version] = "1.3"

projects[taxonomy_title][subdir] = "contrib"
projects[taxonomy_title][version] = "1.5"

projects[token][subdir] = "contrib"
projects[token][version] = "1.6"

projects[viewfield][subdir] = "contrib"
projects[viewfield][version] = "2.0"

projects[views][subdir] = "contrib"
projects[views][version] = "3.11"

projects[views_data_export][subdir] = "contrib"
projects[views_data_export][version] = "3.0-beta8"

projects[views_date_format_sql][subdir] = "contrib"
projects[views_date_format_sql][version] = "3.1"

projects[visualization][subdir] = "contrib"
projects[visualization][version] = "1.0-beta2"

projects[weight][subdir] = "contrib"
projects[weight][version] = "2.5"

projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][version] = "2.2"

projects[xmlsitemap][subdir] = "contrib"
projects[xmlsitemap][version] = "2.2"

; Themes
projects[adminimal_theme][version] = "1.22"

projects[sankofa][version] = "1.0"

projects[zen][version] = "3.1"

projects[zurb_foundation][version] = "4.1"

; Modules
projects[commerce_stamps_com][subdir] = "contrib"
projects[commerce_stamps_com][download][type] = "git"
projects[commerce_stamps_com][download][url] = "http://git.drupal.org/sandbox/andyg5000/1809018.git"
projects[commerce_stamps_com][type] = "module"

projects[commerce_status_alert][subdir] = "contrib"
projects[commerce_status_alert][download][type] = "git"
projects[commerce_status_alert][download][url] = "http://git.drupal.org/sandbox/andyg5000/2354317.git"
projects[commerce_status_alert][type] = "module"

; Libraries
libraries[braintree_php][download][type] = "file"
libraries[braintree_php][download][url] = "https://github.com/braintree/braintree_php/archive/2.40.0.zip"
libraries[braintree_php][directory_name] = "braintree_php"
libraries[braintree_php][type] = "library"

libraries[ckeditor][download][type] = "file"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%203.5.2/ckeditor_3.5.2.zip"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

libraries[colorbox][download][type] = "file"
libraries[colorbox][download][url] = "https://github.com/jackmoore/colorbox/archive/master.zip"
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

libraries[elevatezoom][download][type] = "file"
libraries[elevatezoom][download][url] = "https://github.com/elevateweb/elevatezoom/archive/master.zip"
libraries[elevatezoom][directory_name] = "elevatezoom"
libraries[elevatezoom][type] = "library"

libraries[flexslider][download][type] = "file"
libraries[flexslider][download][url] = "https://github.com/woothemes/FlexSlider/archive/master.zip"
libraries[flexslider][directory_name] = "flexslider"
libraries[flexslider][type] = "library"

libraries[fpdi][download][type] = "file"
libraries[fpdi][download][url] = "https://www.setasign.com/supra/kon2_dl/100933/FPDI-1.6.0.zip"
libraries[fpdi][directory_name] = "fpdi"
libraries[fpdi][type] = "library"
