<?php

/**
 * @file
 *   Provides product customization for medicalidfashions.com
 */


function medicalidfashions_product_form_commerce_cart_add_to_cart_form_alter(&$form, &$form_state, $form_id) {
  $product = $form_state['default_product'];
  if ($product->type == 'bracelets') {
    $form['#submit'][] = 'medicalidfashions_product_add_to_cart_submit';
  }
}


/**
 * Implements hook_commerce_cart_product_add().
 */
function medicalidfashions_product_add_to_cart_submit($form, &$form_state) {
  if (!empty($form_state['values']['field_inch_pricing'][0]['field_inches']['und'][0]['value'])) {
    $wrist_size = $form_state['values']['field_inch_pricing'][0]['field_inches']['und'][0]['value'] . ' ';
  }

  if (!empty($form_state['values']['field_fractions_pricing'][0]['field_fractions']['und'][0]['value'])) {
    $fractions = medidf_get_field_values('field_fractions_pricing');
    $value = $form_state['values']['field_fractions_pricing'][0]['field_fractions']['und'][0]['value'];
    if (!empty($fractions[$value])) {
      $wrist_size .= ' & ' .$fractions[$value];
    }
  }

  if (!empty($wrist_size)) {
    $line_item = $form_state['line_item'];
    $line_item_wrapper = entity_metadata_wrapper('commerce_line_item', $line_item);
    $wrist_size .= ' ' . t('inches');
    $line_item_wrapper->medicalidfashions_line_item_note->set($wrist_size);
    commerce_line_item_save($form_state['line_item']);
  }
}
