<?php

/**
 * @file medidf_product_attributes.module
 * TODO: Enter file description here.
 */


function medidf_product_attributes_theme_registry_alter(&$theme_registry) {
  if ( isset($theme_registry['commerce_product_attributes_item_title']['function']) ) {
    $theme_registry['commerce_product_attributes_item_title']['function'] = 'theme_medidf_product_attributes_item_title';
  }
}

/**
 * OVerrides theme_commerce_product_attributes_item_title($variables).
 */
function theme_medidf_product_attributes_item_title($variables) {
  $output = '';
  return $output;
}