<?php

/**
 * Implements hook_init().
 */
function medidf_rules_init() {
  global $user;
  // If the customer is viewing the cart, invoke the cart view rules event.
  if (arg(0) == 'cart') {
    $order = commerce_cart_order_load($user->uid);
    if (!empty($order)) {
      rules_invoke_all('customer_views_cart', $order);
    }
  }

  // If the customer is viewing checkout, invoke the checkout view rules event.
  if (arg(0) == 'checkout' && !arg(2)) {
    $order = commerce_cart_order_load($user->uid);
    if (!empty($order)) {
      rules_invoke_all('customer_views_checkout', $order);
    }
  }
}
