<?php

/**
 * @file checkout_pane_donations.module
 * Provides an additional checkout pane: Donations.
 */

/**
 * Implements hook_commerce_checkout_pane_info().
 *
 * This is where we define the name of the pane, related information, and
 * the base name of all the form builder functions used to present the
 * pane.
 */
function checkout_pane_donations_commerce_checkout_pane_info() {

  $panes['checkout_pane_donations'] = array(
      'title' => t('Donations'),
      'base' => 'checkout_pane_donations_pane',
      // The checkout page where this should be displayed by default.
      'page' => 'checkout',
      'weight' => -5,
          // The form functions could be found in another file...
          // 'file' => 'includes/pane.inc',
  );

  return $panes;
}

/**
 * Donations Pane: form callback.
 *
 * This is a standard FAPI form which will be presented in the pane.
 * The form gathers and stores information from $order->data, an array which
 * can be populated with free-form keys and values.
 */
function checkout_pane_donations_pane_checkout_form($form, &$form_state, $checkout_pane, $order) {

  if ($_SESSION['aff_flag'] == "a_aid") {
    $pane_form['co_donations'] = array(
        '#type' => 'fieldset',
        '#weight' => 29,
    );

    $pane_form['co_donations']['organization'] = array(
        '#type' => 'select',
        '#title' => t('The American Diabetes Association thanks you for this purchase which has resulted in a generous donation from Medical ID Fashions. This donation will go towards funding diabetes research and patient services through the ADA.'),
        '#default_value' => array('2'),
        '#required' => TRUE,
        '#options' => array(
            2 => t('American Diabetes Association'),
        )
    );

    $pane_form['co_donations']['donation_logos'] = array(
        '#markup' => '
      <div class="donation-logos">
        <img class="media-image" width="172" height="52" src="/sites/default/files/american_diabetes_association_logo-home.jpg" typeof="foaf:Image" alt="">
      </div>',
    );
  } else {
    $pane_form['co_donations'] = array(
        '#type' => 'fieldset',
        '#weight' => 29,
    );

    $pane_form['co_donations']['organization'] = array(
        '#type' => 'select',
        '#title' => t('Choose a medical organization and we will donate $2 out of our own pocket:'),
        '#description' => t('Choose one: ADA, NKF, HCF, EF, CFF, WH or AFA '),
        '#default_value' => array('A'),
        '#required' => TRUE,
        '#options' => array(
            1 => t('- Select an Organization -'),
            2 => t('American Diabetes Association'),
            3 => t('National Kidney Foundation'),
            4 => t('Women Heart'),
            5 => t('Huntsman Cancer Foundation'),
            6 => t('Cystic Fibrosis Foundation'),
            7 => t('Epilepsy Foundation'),
            8 => t('Alzhimers Foundation of America'),
            9 => t('Choose for Me'),
        )
    );

    $pane_form['co_donations']['donation_logos'] = array(
        '#markup' => '
      <div class="donation-logos">
        <img class="media-image" width="172" height="52" src="/sites/default/files/american_diabetes_association_logo-home.jpg" typeof="foaf:Image" alt="">
        <img class="media-image" width="175" height="52" src="/sites/default/files/national_kidney_foundation_home.jpg" typeof="foaf:Image" alt="">
        <img class="media-image" width="175" height="64" src="/sites/default/files/women-heart-logo.jpg" typeof="foaf:Image" alt="">
        <img class="media-image" width="170" height="47" src="/sites/default/files/huntsman_cancer_foundation_logo-home.jpg" typeof="foaf:Image" alt="">
        <img class="media-image" width="175" height="67" src="/sites/default/files/cystic_fibrosis_logo.jpg" typeof="foaf:Image" alt="">
        <img class="media-image" width="174" height="93" src="/sites/default/files/epilepsy_foundation_logo.jpg" typeof="foaf:Image" alt="">
        <img class="media-image" width="175" height="66" src="/sites/default/files/AFA_Logo.jpg" typeof="foaf:Image" alt="">
      </div>',
    );
  }

  return $pane_form;
}

/**
 * Donations pane: validation callback.
 */
function checkout_pane_donations_pane_checkout_form_validate($form, &$form_state, $checkout_pane, $order) {
  if ($form_state['values']['checkout_pane_donations']['co_donations']['organization'] < 2 ||
          $form_state['values']['checkout_pane_donations']['co_donations']['organization'] > 9
  ) {
    form_set_error('organization', t('You must select an organization.'));
    return FALSE;
  }
  return TRUE;
}

// */

/**
 * Donations pane: checkout form submission callback.
 */
function checkout_pane_donations_checkout_form_submit($form, &$form_state, $checkout_pane, $order) {
  if (!empty($form_state['values'][$checkout_pane['pane_id']])) {
    $pane_values = $form_state['values'][$checkout_pane['pane_id']];
    $order->data['organization'] = $pane_values['co_donations']['organization'];
  }
}

/**
   * Terms and Conditions pane: presents the information we've collected in the Review checkout
   * pane.
   */
  /* -- Delete this line if you want to use this function
    function checkout_pane_donations_pane_review($form, $form_state, $checkout_pane, $order) {

    $content['terms_and_conditions'] = array(
    '#type' => 'item',
    '#title' => t('terms_and_conditions'),
    '#markup' => check_plain($order->data['terms_and_conditions']),
    );
    return drupal_render($content);
    }
    // */
